import { checkExceptions, createWaiter, WaiterState } from "@smithy/util-waiter";
import { GetServiceCommand } from "../commands/GetServiceCommand";
const checkState = async (client, input) => {
    let reason;
    try {
        const result = await client.send(new GetServiceCommand(input));
        reason = result;
        try {
            const returnComparator = () => {
                return result.service.status;
            };
            if (returnComparator() === "ACTIVE") {
                return { state: WaiterState.SUCCESS, reason };
            }
        }
        catch (e) { }
        try {
            const returnComparator = () => {
                return result.service.status;
            };
            if (returnComparator() === "CREATE_FAILED_CLEANUP_COMPLETE") {
                return { state: WaiterState.FAILURE, reason };
            }
        }
        catch (e) { }
        try {
            const returnComparator = () => {
                return result.service.status;
            };
            if (returnComparator() === "CREATE_FAILED_CLEANUP_FAILED") {
                return { state: WaiterState.FAILURE, reason };
            }
        }
        catch (e) { }
        try {
            const returnComparator = () => {
                return result.service.status;
            };
            if (returnComparator() === "CREATE_FAILED") {
                return { state: WaiterState.FAILURE, reason };
            }
        }
        catch (e) { }
    }
    catch (exception) {
        reason = exception;
    }
    return { state: WaiterState.RETRY, reason };
};
export const waitForServiceCreated = async (params, input) => {
    const serviceDefaults = { minDelay: 5, maxDelay: 4999 };
    return createWaiter({ ...serviceDefaults, ...params }, input, checkState);
};
export const waitUntilServiceCreated = async (params, input) => {
    const serviceDefaults = { minDelay: 5, maxDelay: 4999 };
    const result = await createWaiter({ ...serviceDefaults, ...params }, input, checkState);
    return checkExceptions(result);
};
